#!/usr/bin/env python3
# Hulot converter: application/x-dvi→application/postscript
# © Reuben Thomas 2002-2023

import contextlib
import sys
import subprocess
from tempfile import TemporaryDirectory

file = sys.argv[1]
ctx_mgr = NamedTemporaryFile() if file == "-" else contextlib.nullcontext()
with ctx_mgr as fp:
    if file == "-": # Standard input can't be a pipe for dvips
        fp.write(sys.stdin.buffer.read())
        file = fp.name
    subprocess.check_call(['dvips', "-o", "-", file])
