#!/usr/bin/env python3

import contextlib
import sys
import subprocess
from tempfile import NamedTemporaryFile

file = sys.argv[1]
ctx_mgr = NamedTemporaryFile() if file == "-" else contextlib.nullcontext()
with ctx_mgr as fp:
    if file == "-":
        fp.write(sys.stdin.buffer.read())
        file = fp.name
    subprocess.check_call(['pdf2ps', file, '-'])
