#!/usr/bin/env python3
# Hulot converter: image/x-epoc-sketch→image/*
# © Reuben Thomas 2002-2023

import os
import sys
import subprocess
import re

conversion = os.path.basename(sys.argv[0])
desttype = re.sub(r"^.*image_", "", conversion).upper()

file = sys.argv[1]
args = ["psiconv", f"--type={desttype}"]
if file != "-":
    args.append(file)
subprocess.check_call(args)
