#!/usr/bin/env perl
# cv
# Convert files from one MIME type to another
# (c) Reuben Thomas 2006-2015

use strict;
use warnings;

use Config;
use File::Basename;
use File::MimeInfo;
use File::Spec::Functions qw(catfile);
use Try::Tiny;

use MIME::Convert;
use RRT::Misc;

my $name = basename($0);
my $converters_dir = $INC{"MIME/Convert.pm"};
$converters_dir =~ s|/Convert.pm||;
$ENV{PATH} .= $Config{path_sep} . catfile($converters_dir, "converters");

# FIXME: Add support for auto-decompression
if ($#ARGV < 1 || $#ARGV > 2) {
  die "Usage: $name IN-FILE OUT-FILE [OUT-MIME-TYPE]\n";
}

my $infile = shift;
my $outfile = shift;
my $intype = getMimeType($infile);
$intype = mimetype($infile) if $intype eq "binary" || $intype eq "application/octet-stream" || $intype eq "text/plain";
my $outtype;
if ($#ARGV == 0) {
  $outtype = shift;
} else {
  $outtype = mimetype($outfile);
}
#print STDERR "$infile $intype $outfile $outtype\n";
if ($outfile eq "-") {
  *OUTFILE = *STDOUT;
} else {
  open OUTFILE, ">$outfile" or die "could not open `$outfile'";
}
try {
  print OUTFILE MIME::Convert::convert($infile, $intype, $outtype, @ARGV);
} catch {
  die "cv: converting $infile ($intype) to $outfile ($outtype): $_";
}
